export const FETCH_TOP_HEADLINES = 'FETCH_TOP_HEADLINES';
export const FETCH_TOP_HEADLINES_SUCCESS = 'FETCH_TOP_HEADLINES_SUCCESS';
export const FETCH_TOP_HEADLINES_ERROR = 'FETCH_TOP_HEADLINES_ERROR';