export const FETCH_URBAN_DEFINITIONS = 'FETCH_URBAN_DEFINITIONS';
export const FETCH_URBAN_DEFINITIONS_SUCCESS = 'FETCH_URBAN_DEFINITIONS_SUCCESS';
export const FETCH_URBAN_DEFINITIONS_ERROR = 'FETCH_URBAN_DEFINITIONS_ERROR';