export const FETCH_DAILY_FORECAST = 'FETCH_DAILY_FORECAST';
export const FETCH_DAILY_FORECAST_SUCCESS = 'FETCH_DAILY_FORECAST_SUCCESS';
export const FETCH_DAILY_FORECAST_ERROR = 'FETCH_DAILY_FORECASE_ERROR';